//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsiSamaDarra2018
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_samadaraEntities : DbContext
    {
        public bd_samadaraEntities()
            : base("name=bd_samadaraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<affecter> affecter { get; set; }
        public DbSet<classe> classe { get; set; }
        public DbSet<eleve> eleve { get; set; }
        public DbSet<exercice> exercice { get; set; }
        public DbSet<inscription> inscription { get; set; }
        public DbSet<parenteleve> parenteleve { get; set; }
        public DbSet<servive> servive { get; set; }
        public DbSet<tuteur> tuteur { get; set; }
    }
}
