//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsiSamaDarra2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class parenteleve
    {
        public int idEleve { get; set; }
        public int idParent { get; set; }
    }
}
